DEFAULT_USER="default_user"
DEFAULT_LOCATION='W Quay Rd, Southampton SO15 1AG' # Leonardo Royal Hotel (30063400)
DEFAULT_COORDS = [-1.4071556, 50.9000224]

POST_DEFAULT_USER="post_user"
POST_DEFAULT_LOCATION="Spain"
POST_DEFAULT_COORDS=DEFAULT_COORDS

LOCAL_USER="local_user"
LOCAL_DEFAULT_LOCATION="UK"
LOCAL_DEFAULT_COORDS=DEFAULT_COORDS

MOCK=True

# USER_REDIS_PORT = 6379
# NEWS_REDIS_PORT = 6380